apiVersion: v1
kind: Service
metadata:
  name: svc-nexusdeploy
  namespace: tekton
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: myapp
